"use strict";
exports.__esModule = true;
var Autor_1 = require("./libreta/Autor/Autor");
var Nota_1 = require("./libreta/Nota/Nota");
var Libreta_1 = require("./libreta/Libreta");
var autor1 = new Autor_1["default"]();
autor1.setNombre("Facu");
autor1.setApellido("Benitez");
autor1.setDni(12345678);
var nota1 = new Nota_1["default"](autor1);
nota1.setId(1);
nota1.setContenido("pasaron cosas, pusimos metas optimistas, hace 4 años que no crecemos");
var autor2 = new Autor_1["default"]();
autor2.setNombre("Abi");
autor2.setApellido("Gomez");
autor2.setDni(78945612);
var nota2 = new Nota_1["default"](autor2);
nota2.setId(2);
nota2.setContenido("Ay caramba, a la grande le puse cuca, plan dental lisa necesita fresos");
var autor3 = new Autor_1["default"]();
autor3.setNombre("Mauricio");
autor3.setApellido("Macri");
autor3.setDni(45612378);
var nota3 = new Nota_1["default"](autor3);
nota3.setId(3);
nota3.setContenido("pasaron cosas, pusimos metas optimistas, hace 4 años que no crecemos");
console.log(nota1);
console.log(nota2);
console.log(nota3);
var listado = new Libreta_1["default"]();
listado.addNota(nota1);
listado.addNota(nota2);
listado.addNota(nota3);
console.log(listado.getAllLista());
console.log(listado.getNotasForDni(45612378));
