var libreta = require('./libreta/Libreta');
var libre = new libreta();
var titulo = "frases de macri";
var contenido = "pasaron cosas, pusimos metas optimistas, hace 4 años que no crecemos";
var fecha = "21/05/2021";
var nombre = "Mauricio";
var apellido = "Macri";
var dni = 12345678;
libre.newNota(titulo, contenido, fecha, nombre, apellido, dni);
titulo = "frases simpson";
contenido = "Ay caramba, a la grande le puse cuca, plan dental lisa necesita fresos";
fecha = "20/05/2021";
nombre = "Facu";
apellido = "Benitez";
dni = 45679812;
libre.newNota(titulo, contenido, fecha, nombre, apellido, dni);
titulo = "patrones de diseño";
contenido = "Singleton, factory, builder, MVC";
fecha = "23/05/2019";
nombre = "Facu";
apellido = "Benitez";
dni = 45678912;
libre.newNota(titulo, contenido, fecha, nombre, apellido, dni);
titulo = "lenguajes de programacion";
contenido = "C++, PHP, JavaScript, Java, C#, C";
fecha = "25/11/20";
nombre = "Nico";
apellido = "Gutierrez";
dni = 45678932;
libre.newNota(titulo, contenido, fecha, nombre, apellido, dni);
var lista = libre.getAllLista();
var notasFacu = libre.getNotasForAutor('Facu');
console.log(lista);
console.log(notasFacu);
